name: hawihub
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  # CORE PACKAGES
  cupertino_icons: ^1.0.6
  shared_preferences: ^2.2.2
  animated_splash_screen: ^1.3.0
  sizer: ^2.0.15
  flutter_bloc: ^8.1.1
  bloc: ^8.1.1
  equatable: ^2.0.5
  dartz: ^0.10.1
  get_it: ^7.2.0
  dio: ^5.4.1
  image_picker:
  fluttertoast: ^8.2.4
  shimmer: ^3.0.0
  share_plus: any
  open_file_plus: ^3.4.1+1
  file_picker: ^8.0.2
  firebase_messaging:
  intl:


  # AUTH PACKAGES
  flutter_facebook_auth: ^6.2.0
  google_sign_in: ^6.2.1


  # PLACES PACKAGES
  flutter_rating_bar: ^4.0.1
  carousel_slider: ^4.2.1
  geolocator: ^10.0.0
  location_picker_flutter_map:
  flutter_geolocation_service: ^0.1.0
  connectivity_plus: ^6.0.1
  timeago:

  # CHATS PACKAGES
  voice_message_package: ^2.1.4
  audioplayers: any
  #  record: ^5.0.5
  path_provider:
  permission_handler:

  # PAYMENT PACKAGE
  my_fatoorah: ^3.2.0
  app_links: ^6.1.1
  firebase_core: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/audios/
    - assets/images/icons/
    - assets/images/app_bar_backgrounds/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_intl:
  enabled: true
