import 'package:hawihub/src/modules/games/data/models/game.dart';
import 'package:hawihub/src/modules/games/data/models/player.dart';
import 'package:hawihub/src/modules/main/data/models/app_notification.dart';
import 'package:hawihub/src/modules/places/data/models/place.dart';
import 'package:hawihub/src/modules/places/data/models/place_location.dart';

List<Place> dummyPlaces = [
  Place(
    id: 1,
    name: "ملعب القاهرة الدولي",
    address: "شارع 26 يوليو، قصر النيل، القاهرة",
    workingHours: [],
    //location: PlaceLocation(longitude: 31.2357, latitude: 30.0483),
    location: PlaceLocation(longitude: 31.2357, latitude: 30.0483),
    description: "ملعب متعدد الاستخدامات، يستضيف المباريات الدولية والمحلية.",
    sport: 1,
    price: 500.0,
    ownerId: 1,
    images: ["", ""],
    totalGames: 100,
    totalRatings: 250,
    rating: 4.5,
    feedbacks: [],
    ownerName: "إتحاد الكرة المصري",
    ownerImage: "",
    citId: 1,
    approvalStatus: 1,
    availableGender: Gender.both,
    deposit: 100,
    isShared: false,
  ),
  Place(
    id: 2,
    name: "استاد برج العرب",
    address: "الكيلو 21، طريق مصر إسكندرية الصحراوي",
    workingHours: [],
    //location: PlaceLocation(longitude: "29.8834", latitude: "31.1862"),
    location: PlaceLocation(longitude: 31.2357, latitude: 30.0483),
    description:
        "أحد أكبر الملاعب في مصر، ويستضيف العديد من الفعاليات الرياضية.",
    sport: 1,
    price: 600.0,
    ownerId: 2,
    images: ["", ""],
    totalGames: 80,
    totalRatings: 150,
    rating: 4.7,
    feedbacks: [],
    ownerName: "إتحاد الكرة المصري",
    ownerImage: "",
    citId: 2,
    approvalStatus: 1,
    availableGender: Gender.both,
    deposit: 150,
    isShared: true,
  ),
  Place(
    id: 3,
    name: "استاد القاهرة",
    address: "شارع 26 يوليو، قصر النيل، القاهرة",
    workingHours: [],
    //location: PlaceLocation(longitude: "31.2357", latitude: "30.0483"),
    location: PlaceLocation(longitude: 31.2357, latitude: 30.0483),
    description: "يستضيف المباريات النهائية للكثير من البطولات.",
    sport: 1,
    price: 700.0,
    ownerId: 3,
    images: ["", ""],
    totalGames: 90,
    totalRatings: 300,
    rating: 4.8,
    feedbacks: [],
    ownerName: "إتحاد الكرة المصري",
    ownerImage: "",
    citId: 1,
    approvalStatus: 1,
    availableGender: Gender.both,
    deposit: 200,
    isShared: false,
  ),
];
List<AppNotification> dummyNotifications = [
  AppNotification(
    id: 1,
    title: "Welcome!",
    body: "Thanks for joining our platform.",
    receiverId: 101,
    image: "https://example.com/images/welcome.png",
    link: "https://example.com/welcome",
    dateTime: DateTime.now().subtract(Duration(hours: 2)),
  ),
  AppNotification(
    id: 2,
    title: "New Update Available",
    body: "Check out the latest features in the new update.",
    receiverId: 101,
    image: "https://example.com/images/update.png",
    link: "https://example.com/update",
    dateTime: DateTime.now().subtract(Duration(days: 1)),
  ),
  AppNotification(
    id: 3,
    title: "Reminder",
    body: "Don't forget about the event tomorrow!",
    receiverId: 101,
    dateTime: DateTime.now().subtract(Duration(hours: 6)),
  ),
  AppNotification(
    id: 4,
    title: "Discount Alert",
    body: "Exclusive discount just for you. Don't miss it!",
    receiverId: 101,
    image: "https://example.com/images/discount.png",
    dateTime: DateTime.now().subtract(Duration(minutes: 30)),
  ),
  AppNotification(
    id: 5,
    title: "Maintenance Notice",
    body: "Scheduled maintenance will occur tomorrow at 2 AM.",
    receiverId: 101,
    link: "https://example.com/maintenance",
    dateTime: DateTime.now().subtract(Duration(hours: 12)),
  ),
];

List<String> dummyBanners = [
  "",
  "",
  "",
];

List<Game> dummyGames = [
  Game(
    id: 1,
    sportName: "Football",
    price: 150.0,
    date: DateTime.now().add(Duration(days: 2)),
    placeId: 10,
    maxPlayers: 10,
    minPlayers: 5,
    hours: 2.0,
    sportImageUrl: "https://example.com/images/football.png",
    placeAddress: "Cairo Stadium, Cairo",
    placeName: "Cairo Stadium",
    isPublic: true,
    startTime: DateTime.now().add(Duration(days: 2, hours: 5)),
    endTime: DateTime.now().add(Duration(days: 2, hours: 7)),
    deadline: DateTime.now().add(Duration(days: 1, hours: 5)),
    sportId: 101,
    players: [
      GamePlayer(id: 1, name: "Player 1", imageUrl: "", isHost: false),
      GamePlayer(id: 1, name: "Player 1", imageUrl: "", isHost: false),
      GamePlayer(id: 1, name: "Player 1", imageUrl: "", isHost: false),
    ],
    host: Host(
        id: 1,
        name: "Host 1",
        isHost: true,
        imageUrl: "",
        birthDate: "1990-01-01"),
  ),
  Game(
    id: 2,
    sportName: "Basketball",
    price: 200.0,
    date: DateTime.now().add(Duration(days: 5)),
    placeId: 20,
    maxPlayers: 10,
    minPlayers: 5,
    hours: 1.5,
    sportImageUrl: "https://example.com/images/basketball.png",
    placeAddress: "Zamalek Club, Cairo",
    placeName: "Zamalek Club",
    isPublic: false,
    startTime: DateTime.now().add(Duration(days: 5, hours: 4)),
    endTime: DateTime.now().add(Duration(days: 5, hours: 5, minutes: 30)),
    deadline: DateTime.now().add(Duration(days: 4, hours: 4)),
    sportId: 102,
    players: [
      GamePlayer(id: 1, name: "Player 1", imageUrl: "", isHost: false),
      GamePlayer(id: 1, name: "Player 1", imageUrl: "", isHost: false),
      GamePlayer(id: 1, name: "Player 1", imageUrl: "", isHost: false),
    ],
    host: Host(
        id: 1,
        name: "Host 1",
        isHost: true,
        imageUrl: "",
        birthDate: "1990-01-01"),
  ),
  Game(
    id: 1,
    sportName: "Football",
    price: 150.0,
    date: DateTime.now().add(Duration(days: 2)),
    placeId: 10,
    maxPlayers: 10,
    minPlayers: 5,
    hours: 2.0,
    sportImageUrl: "https://example.com/images/football.png",
    placeAddress: "Cairo Stadium, Cairo",
    placeName: "Cairo Stadium",
    isPublic: true,
    startTime: DateTime.now().add(Duration(days: 2, hours: 5)),
    endTime: DateTime.now().add(Duration(days: 2, hours: 7)),
    deadline: DateTime.now().add(Duration(days: 1, hours: 5)),
    sportId: 101,
    players: [
      GamePlayer(id: 1, name: "Player 1", imageUrl: "", isHost: false),
      GamePlayer(id: 1, name: "Player 1", imageUrl: "", isHost: false),
      GamePlayer(id: 1, name: "Player 1", imageUrl: "", isHost: false),
    ],
    host: Host(
        id: 1,
        name: "Host 1",
        isHost: true,
        imageUrl: "",
        birthDate: "1990-01-01"),
  ),
  Game(
    id: 2,
    sportName: "Basketball",
    price: 200.0,
    date: DateTime.now().add(Duration(days: 5)),
    placeId: 20,
    maxPlayers: 10,
    minPlayers: 5,
    hours: 1.5,
    sportImageUrl: "https://example.com/images/basketball.png",
    placeAddress: "Zamalek Club, Cairo",
    placeName: "Zamalek Club",
    isPublic: false,
    startTime: DateTime.now().add(Duration(days: 5, hours: 4)),
    endTime: DateTime.now().add(Duration(days: 5, hours: 5, minutes: 30)),
    deadline: DateTime.now().add(Duration(days: 4, hours: 4)),
    sportId: 102,
    players: [
      GamePlayer(id: 1, name: "Player 1", imageUrl: "", isHost: false),
      GamePlayer(id: 1, name: "Player 1", imageUrl: "", isHost: false),
      GamePlayer(id: 1, name: "Player 1", imageUrl: "", isHost: false),
    ],
    host: Host(
        id: 1,
        name: "Host 1",
        isHost: true,
        imageUrl: "",
        birthDate: "1990-01-01"),
  ),
  Game(
    id: 1,
    sportName: "Football",
    price: 150.0,
    date: DateTime.now().add(Duration(days: 2)),
    placeId: 10,
    maxPlayers: 10,
    minPlayers: 5,
    hours: 2.0,
    sportImageUrl: "https://example.com/images/football.png",
    placeAddress: "Cairo Stadium, Cairo",
    placeName: "Cairo Stadium",
    isPublic: true,
    startTime: DateTime.now().add(Duration(days: 2, hours: 5)),
    endTime: DateTime.now().add(Duration(days: 2, hours: 7)),
    deadline: DateTime.now().add(Duration(days: 1, hours: 5)),
    sportId: 101,
    players: [
      GamePlayer(id: 1, name: "Player 1", imageUrl: "", isHost: false),
      GamePlayer(id: 1, name: "Player 1", imageUrl: "", isHost: false),
      GamePlayer(id: 1, name: "Player 1", imageUrl: "", isHost: false),
    ],
    host: Host(
        id: 1,
        name: "Host 1",
        isHost: true,
        imageUrl: "",
        birthDate: "1990-01-01"),
  ),
  Game(
    id: 2,
    sportName: "Basketball",
    price: 200.0,
    date: DateTime.now().add(Duration(days: 5)),
    placeId: 20,
    maxPlayers: 10,
    minPlayers: 5,
    hours: 1.5,
    sportImageUrl: "https://example.com/images/basketball.png",
    placeAddress: "Zamalek Club, Cairo",
    placeName: "Zamalek Club",
    isPublic: false,
    startTime: DateTime.now().add(Duration(days: 5, hours: 4)),
    endTime: DateTime.now().add(Duration(days: 5, hours: 5, minutes: 30)),
    deadline: DateTime.now().add(Duration(days: 4, hours: 4)),
    sportId: 102,
    players: [
      GamePlayer(id: 1, name: "Player 1", imageUrl: "", isHost: false),
      GamePlayer(id: 1, name: "Player 1", imageUrl: "", isHost: false),
      GamePlayer(id: 1, name: "Player 1", imageUrl: "", isHost: false),
    ],
    host: Host(
        id: 1,
        name: "Host 1",
        isHost: true,
        imageUrl: "",
        birthDate: "1990-01-01"),
  ),
];
